export const STR = {
  toast: {
    copied: (n) => `已复制 ${n} 个`,
    copyNone: '未勾选任何记录',
    pasted: (n) => `已粘贴 ${n} 个`,
    deleted: '已删除',
    saved: '已保存',
    imported: '导入成功',
    importFail: '导入失败：格式不正确',
    backupOk: '已备份',
    backupFail: '备份失败',
    unselected: '已取消勾选',
    tagAdded: '标签已添加',
    tagUpdated: '标签已更新',
    tagDeleted: '标签已删除',
    copyBlock: '已复制 1 个，关闭后切换日期或悬停到目标位置，按 Ctrl/⌘+V 粘贴',
    pasteResult: (n, anchored) => `已粘贴 ${n} 个${anchored ? '（锚定位置）' : '（原时间）'}`,
    contextSelected: (n) => `已勾选 ${n} 个（Delete 删除 / Ctrl⌘+C 复制）`,
    backupPathUpdated: '备份路径已更新',
    backupPathReset: '已恢复默认路径',
    importCount: (n) => `已导入 ${n} 条`,
    backupTauriOnly: '自动备份需桌面应用（Tauri）支持',
    backupMigrated: (n) => `已迁移 ${n} 个备份文件`,
    importCountTo: (n, date) => `已导入 ${n} 条到 ${date}`,
  },
  confirm: {
    deleteBlock: '确定删除该时间块？',
    deleteSelected: (n) => `确定删除选中的 ${n} 个时间块？`,
    deleteTag: (name) => `确定删除标签"${name}"？`,
    renameTag: (old, name) => `标签"${old}"已改名为"${name}"，是否将已有记录中的"${old}"替换为"${name}"？`,
    deleteAll: '确定删除所有数据？此操作不可恢复。',
    deleteRange: (d1, d2) => `确定删除 ${d1} 至 ${d2} 的数据？`,
    deleteDay: (d) => `确定删除 ${d} 的全部记录？`,
    deleteSelectedBlock: (n) => `将删除 ${n} 个时间块，确定？`,
    backupPathReset: '将备份位置恢复为默认（AppData），并迁移已有备份文件？',
    importFileError: '文件格式不对，缺少 days 字段。',
    importParseError: (msg) => `解析失败：${msg}`,
    importNoRecords: '未解析到有效记录，请检查文本格式。',
    importComplete: '导入完成。',
    selectDateRange: '请选择起止日期。',
    noRecordsInRange: '该日期范围内没有记录。',
    deleteRangeConfirm: (days, count) => `将删除 ${days} 天、共 ${count} 条记录，确定？`,
    noRecords: '没有任何记录。',
    deleteAllConfirm: (days, count) => `确定删除全部 ${days} 天、共 ${count} 条记录？此操作不可恢复。`,
    discardEdit: '放弃编辑？未保存的内容将丢失。',
  },
  btn: {
    ok: '确定',
    cancel: '取消',
    close: '关闭',
    save: '保存',
    delete: '删除',
    copy: '复制',
  },
  update: {
    title: (v) => `发现新版本 ${v}`,
    published: (d) => `发布日期：${d}`,
    changelog: '更新内容',
    now: '现在更新',
    onExit: '下载后退出时更新',
    skip: '跳过此版本',
    dismiss: '忽略',
    downloading: '正在下载...',
    installing: '正在安装...',
    willInstallOnExit: '将在退出时安装更新',
    done: '更新完成，即将重启',
    noUpdate: '已是最新版本',
    checkFailed: '检查更新失败，请检查网络',
    downloadFailed: '下载失败',
    installFailed: '安装失败',
    retry: '重试',
    cancel: '取消',
    openFolder: '打开下载文件夹',
    copyPath: '复制路径',
    checking: '检查中...',
    checkUpdate: '检查更新',
    autoUpdate: '自动更新',
    autoUpdateDesc: '启动时自动检查更新（默认关闭）',
    pendingTitle: (v) => `上次下载的 ${v} 尚未安装`,
    pendingDesc: '是否现在安装？',
    pendingInstall: '现在安装',
    pendingDismiss: '忽略',
    versionAhead: '你的版本已经高于云端了，你还想怎么样嘛',
  },
}
