export const STR = {
  toast: {
    copied: (n) => `已复制 ${n} 个`,
    copyNone: '未勾选任何记录',
    pasted: (n) => `已粘贴 ${n} 个`,
    deleted: '已删除',
    saved: '已保存',
    imported: '导入成功',
    importFail: '导入失败：格式不正确',
    backupOk: '已备份',
    backupFail: '备份失败',
    unselected: '已取消勾选',
    tagAdded: '标签已添加',
    tagUpdated: '标签已更新',
    tagDeleted: '标签已删除',
    copyBlock: '已复制 1 个，关闭后切换日期或悬停到目标位置，按 Ctrl/⌘+V 粘贴',
    pasteResult: (n, anchored) => `已粘贴 ${n} 个${anchored ? '（锚定位置）' : '（原时间）'}`,
    contextSelected: (n) => `已勾选 ${n} 个（Delete 删除 / Ctrl⌘+C 复制）`,
    backupPathUpdated: '备份路径已更新',
    backupPathReset: '已恢复默认路径',
    importCount: (n) => `已导入 ${n} 条`,
    backupTauriOnly: '自动备份需桌面应用（Tauri）支持',
    backupMigrated: (n) => `已迁移 ${n} 个备份文件`,
    importCountTo: (n, date) => `已导入 ${n} 条到 ${date}`,
  },
  confirm: {
    deleteBlock: '确定删除该时间块？',
    deleteSelected: (n) => `确定删除选中的 ${n} 个时间块？`,
    deleteTag: (name) => `确定删除标签"${name}"？`,
    renameTag: (old, name) => `标签"${old}"已改名为"${name}"，是否将已有记录中的"${old}"替换为"${name}"？`,
    deleteAll: '确定删除所有数据？此操作不可恢复。',
    deleteRange: (d1, d2) => `确定删除 ${d1} 至 ${d2} 的数据？`,
    deleteDay: (d) => `确定删除 ${d} 的全部记录？`,
    deleteSelectedBlock: (n) => `将删除 ${n} 个时间块，确定？`,
    backupPathReset: '将备份位置恢复为默认（AppData），并迁移已有备份文件？',
    importFileError: '文件格式不对，缺少 days 字段。',
    importParseError: (msg) => `解析失败：${msg}`,
    importNoRecords: '未解析到有效记录，请检查文本格式。',
    importComplete: '导入完成。',
    selectDateRange: '请选择起止日期。',
    noRecordsInRange: '该日期范围内没有记录。',
    deleteRangeConfirm: (days, count) => `将删除 ${days} 天、共 ${count} 条记录，确定？`,
    noRecords: '没有任何记录。',
    deleteAllConfirm: (days, count) => `确定删除全部 ${days} 天、共 ${count} 条记录？此操作不可恢复。`,
    discardEdit: '放弃编辑？未保存的内容将丢失。',
  },
  btn: {
    ok: '确定',
    cancel: '取消',
    close: '关闭',
    save: '保存',
    delete: '删除',
    copy: '复制',
  },
  update: {
    title: (v) => `发现新版本 ${v}`,
    published: (d) => `发布日期：${d}`,
    changelog: '更新内容',
    now: '现在更新',
    onExit: '下载后退出时更新',
    skip: '跳过此版本',
    dismiss: '忽略',
    downloading: '正在下载...',
    installing: '正在安装...',
    willInstallOnExit: '将在退出时安装更新',
    done: '更新完成，即将重启',
    noUpdate: '已是最新版本',
    checkFailed: '检查更新失败，请检查网络',
    downloadFailed: '下载失败',
    installFailed: '安装失败',
    retry: '重试',
    cancel: '取消',
    openFolder: '打开下载文件夹',
    copyPath: '复制路径',
    checking: '检查中...',
    checkUpdate: '检查更新',
    autoUpdate: '自动更新',
    autoUpdateDesc: '启动时自动检查更新（默认关闭）',
    pendingTitle: (v) => `上次下载的 ${v} 尚未安装`,
    pendingDesc: '是否现在安装？',
    pendingInstall: '现在安装',
    pendingDismiss: '忽略',
    versionAhead: '你的版本已经高于云端了，你还想怎么样嘛',
  },
  batchCreate: {
    title: '批量创建时间块',
    placeholder: '做了什么\n标签,标签\n0900 1100\n备注内容\n---\n下一个块...',
    preview: (n) => `预览：${n} 个时间块`,
    create: '创建',
    created: (n) => `已创建 ${n} 个时间块`,
    defaultTitle: '(未命名)',
  },
  settings: {
    // ── General ──
    title: '设置',
    helpButton: '打开',

    // ── Nav ──
    navBasic: '基础',
    navEditor: '编辑器',
    navAppearance: '外观',
    navFiles: '文件',

    // ── Basic ──
    version: '当前版本',
    checkUpdate: '检查更新',
    autoUpdate: '自动更新',
    language: '语言',
    help: '帮助弹窗',
    sectionStartup: '启动',
    autoScroll: '打开时滚到当前时间',

    // ── Editor ──
    sectionEditor: '时间块编辑器 (T & 鼠标)',
    defaultDuration: '默认时长',
    markdownPreview: 'Markdown 预览',
    sectionBatchCreate: 'N 模式创建时间块',
    checkBeforeCreate: '保存前检查解析结果',
    copyAfterCreate: '创建后复制到剪贴板',
    tagDelimiters: '标签分隔符',

    // ── Appearance ──
    fontFamily: '字体',
    fontSize: '字体大小',
    zoom: '缩放比例',
    blockOpacity: '时间块透明度',
    borderless: '无边框窗口',

    // ── Files ──
    sectionExport: '导出',
    exportTimestamp: '文件名加时间戳',
    exportDialog: '导出时弹出保存对话框',
    sectionBackup: '备份',
    backupPath: '备份路径',
    backupOn: '启用自动备份（Tauri）',
    keepDays: '只保留最近 N 天数据',

    // ── Descriptions ──
    descDefaultDuration: '按 T 键快速创建时默认时间块长度',
    descTagDelimiters: '批量创建（n）时拆分标签的字符，如 , ， .',
    descAutoScroll: '启动时自动将时间轴滚动到当前时间所在位置',
    descCheckBeforeCreate: '启用后批量创建前弹出预览确认，关闭则直接创建',
    descCopyAfterCreate: '创建后将格式化文本复制到剪贴板，便于粘贴恢复',
    descFontFamily: '输入字体名称，如 JetBrains Mono；留空恢复默认',
    descZoom: '25%–400%，默认 100%',
    descBlockOpacity: '调整时间块颜色的透明度',
    sectionBlockDisplay: '时间块',
    showBlockTitle: '显示标题',
    showBlockTime: '显示时间',
    showBlockTags: '显示标签',
    showBlockNote: '显示备注',
    showBlockColorBar: '显示左侧颜色条',
    descBorderless: '启用后隐藏原生标题栏，顶部右侧显示窗口控制按钮',
    descExportTimestamp: '例：timelog-backup-2026-07-04-1730.json',
    descExportDialog: '导出时弹出系统文件对话框选择保存位置',
    descBackupPath: '输入绝对路径，留空则使用 AppData',
    descBackupOn: '关闭后不再自动写入备份文件，避免数据量大时影响性能',
    descKeepDays: '0 = 保留全部；设 7 则仅保留最近 7 个有数据的天',
    descCheckUpdate: '手动检测是否有新版本可下载',
    descAutoUpdate: '启动时自动检查更新（默认关闭）',
    descLanguage: '界面显示语言（尚未开放）',
    descHelp: '查看键盘快捷键和操作指南',
    descFontSize: '调整界面文字大小（尚未开放）',
    descMarkdownPreview: '编辑时所见即所得渲染 Markdown，关闭后使用纯文本',
    batchMarkdownPreview: 'N - Markdown 预览',
    descBatchMarkdownPreview: 'N 键批量创建时所见即所得渲染 Markdown，关闭后使用纯文本',
    tabToIndent: 'Tab 插入缩进',
    descTabToIndent: '开启后在行首使用 Tab 插入缩进；ESC 切换编辑/导航模式',
    batchTabToIndent: 'Tab 插入缩进',
    descBatchTabToIndent: '开启后在 N 键行首使用 Tab 插入缩进；ESC 切换编辑/导航模式',
    editorFontSize: '编辑器字号',
    descEditorFontSize: '编辑框内文字大小，10–28px',

    // ── Restore ──
    restoreDefault: '恢复默认设置',
    restoreCategory: '恢复本栏默认',
    placeholderFontFamily: '默认（系统字体）',
    placeholderFontSize: '待实现',
    placeholderBackupPath: '默认（AppData）',
  },

  stats: {
    title: '统计',
    addView: '+ 添加视图',
    noData: '暂无数据',
    noChart: '点击 [+ 添加视图] 创建第一个图表',
    timeRange: '时间范围',
    timeToday: '今天',
    time24h: '24h',
    timeWeek: '本周',
    time168h: '24×7h',
    time7d: '最近 7 天',
    timeMonth: '本月',
    timeCustom: '自定义',
    invalidDate: '日期格式无效，请输入 yyyy-mm-dd',
    createTitle: '新建视图',
    viewName: '视图名称',
    chartType: '图表类型',
    pie: '饼图',
    bar: '柱状图',
    onlyFirstTag: '只记录第一个标签',
    showLegend: '显示图例',
    legendData: '图例显示数据',
    legendPercent: '图例显示占比',
    chartData: '图中显示数据',
    chartPercent: '图中显示占比',
    interactive: '图表交互',
    deleteView: '删除此视图',
    includeUntagged: '包含无标签时间块',
    excludeTags: '排除标签（逗号分隔）',
    filterGroups: '筛选标签组（不选=全部）',
    untagged: '无标签',
    settings: '视图设置',
    confirm: '确认',
    cancel: '取消',
  },

  help: {
    title: '操作指南',
    sectionBlocks: '时间块操作',
    helpBlocks: [
      '在时间轴上<b>拖动</b>选择时段，松开后填写内容',
      '<b>左键</b>点击色块编辑',
      '<b>右键</b>勾选/取消色块（多选）',
      '拖动色块<b>顶部/底部边缘</b>调整时长',
    ],
    sectionShortcuts: '快捷键',
    helpShortcuts: [
      'Esc  关闭弹窗 / 取消选择',
      'Delete  删除选中的时间块',
      'Ctrl + C  复制选中',
      'Ctrl + V  粘贴',
      'Ctrl + A  全选当天时间块',
      'T  快速记录当前时间',
      'N  批量创建',
      'S  打开统计视图',
      'P  导出文本',
      '← →  切换上/下一天',
      '↑ ↓  拖动时微调时间（±1 分钟）',
      '?  打开此帮助',
    ],
    sectionWindow: '窗口操作',
    helpWindow: [
      '<b>拖拽</b>标题栏移动窗口',
      '<b>双击</b>标题栏切换最大化/还原',
      '<b>单击</b>日期弹出日历选择器',
      '<b>双击</b>日期跳转到指定日期',
    ],
    sectionStats: '统计视图',
    helpStats: [
      '时间范围筛选：今天 / 24小时 / 本周 / 最近7天 / 本月 / 自定义',
      '支持<b>饼图</b>和<b>柱状图</b>两种图表',
      '开启<b>"图表交互"</b>后 hover 显示数据',
      '每张卡片可配置<b>自定义名称</b>',
    ],
    sectionBackup: '数据备份',
    helpBackup: [
      '桌面应用<b>自动静默备份</b>到 <code>timelog_data</code> 文件夹',
      '自动备份包含<b>数据、标签、统计视图、设置</b>',
      '每天首次操作时生成备份，<b>最多保留 4 个</b>',
    ],
    sectionExport: '导出/导入',
    helpExport: [
      '<b>"导出文本"</b>（P）：复制当天内容',
      '<b>"导出备份"</b>：可按内容选择导出（数据 / 标签 / 统计 / 设置）',
      '<b>"导入"</b>：JSON 备份还原，同样支持按内容选择',
      '<b>"文本导入"</b>：解析之前导出的文本',
    ],
    footer: 'Made by Yves / 陈虹宇 · 2026',
    close: '关闭',
  },
}
